# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build and test
on: [push, pull_request]
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: install firebase-tools
        run: |
          npm -i -g firebase-tools
          firebase --version
