# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build and test
on: [push, pull_request]
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2

      - name: build and run tests
        run: firebase
